version: '3'

services:
  app:
    container_name: project-rails-test
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "33003:3000"
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
